export interface IndianLocationItem {
  id: string;
  city: string;
  district: string;
  state: string;
  latitude: number;
  longitude: number;
  region: string;
}

export const POPULAR_INDIAN_LOCATIONS: IndianLocationItem[] = [
  // Uttar Pradesh & NCR
  {
    id: 'noida_up',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    latitude: 28.5355,
    longitude: 77.391,
    region: 'North India',
  },
  {
    id: 'greater_noida_up',
    city: 'Greater Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    latitude: 28.4744,
    longitude: 77.504,
    region: 'North India',
  },
  {
    id: 'dadri_up',
    city: 'Dadri',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    latitude: 28.552,
    longitude: 77.554,
    region: 'North India',
  },
  {
    id: 'delhi_ncr',
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    latitude: 28.6139,
    longitude: 77.209,
    region: 'North India',
  },
  {
    id: 'ghaziabad_up',
    city: 'Ghaziabad',
    district: 'Ghaziabad',
    state: 'Uttar Pradesh',
    latitude: 28.6692,
    longitude: 77.4538,
    region: 'North India',
  },
  {
    id: 'meerut_up',
    city: 'Meerut',
    district: 'Meerut',
    state: 'Uttar Pradesh',
    latitude: 28.9845,
    longitude: 77.7064,
    region: 'North India',
  },
  {
    id: 'agra_up',
    city: 'Agra',
    district: 'Agra',
    state: 'Uttar Pradesh',
    latitude: 27.1767,
    longitude: 78.0081,
    region: 'North India',
  },
  {
    id: 'varanasi_up',
    city: 'Varanasi',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    latitude: 25.3176,
    longitude: 82.9739,
    region: 'North India',
  },
  {
    id: 'lucknow_up',
    city: 'Lucknow',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    latitude: 26.8467,
    longitude: 80.9462,
    region: 'North India',
  },

  // Maharashtra
  {
    id: 'nagpur_mh',
    city: 'Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    latitude: 21.1458,
    longitude: 79.0882,
    region: 'Central India',
  },
  {
    id: 'amravati_mh',
    city: 'Amravati',
    district: 'Amravati',
    state: 'Maharashtra',
    latitude: 20.9374,
    longitude: 77.7796,
    region: 'Central India',
  },
  {
    id: 'nashik_mh',
    city: 'Nashik',
    district: 'Nashik',
    state: 'Maharashtra',
    latitude: 19.9975,
    longitude: 73.7898,
    region: 'Western India',
  },
  {
    id: 'pune_mh',
    city: 'Pune',
    district: 'Pune',
    state: 'Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    region: 'Western India',
  },
  {
    id: 'aurangabad_mh',
    city: 'Chhatrapati Sambhajinagar',
    district: 'Aurangabad',
    state: 'Maharashtra',
    latitude: 19.8762,
    longitude: 75.3433,
    region: 'Western India',
  },
  {
    id: 'akola_mh',
    city: 'Akola',
    district: 'Akola',
    state: 'Maharashtra',
    latitude: 20.7002,
    longitude: 77.0082,
    region: 'Central India',
  },

  // Punjab & Haryana
  {
    id: 'ludhiana_pb',
    city: 'Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    latitude: 30.901,
    longitude: 75.8573,
    region: 'North India',
  },
  {
    id: 'amritsar_pb',
    city: 'Amritsar',
    district: 'Amritsar',
    state: 'Punjab',
    latitude: 31.634,
    longitude: 74.8723,
    region: 'North India',
  },
  {
    id: 'bhatinda_pb',
    city: 'Bathinda',
    district: 'Bathinda',
    state: 'Punjab',
    latitude: 30.211,
    longitude: 74.9455,
    region: 'North India',
  },
  {
    id: 'karnal_hr',
    city: 'Karnal',
    district: 'Karnal',
    state: 'Haryana',
    latitude: 29.6857,
    longitude: 76.9905,
    region: 'North India',
  },
  {
    id: 'hisar_hr',
    city: 'Hisar',
    district: 'Hisar',
    state: 'Haryana',
    latitude: 29.1492,
    longitude: 75.7217,
    region: 'North India',
  },

  // Madhya Pradesh
  {
    id: 'indore_mp',
    city: 'Indore',
    district: 'Indore',
    state: 'Madhya Pradesh',
    latitude: 22.7196,
    longitude: 75.8577,
    region: 'Central India',
  },
  {
    id: 'bhopal_mp',
    city: 'Bhopal',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    latitude: 23.2599,
    longitude: 77.4126,
    region: 'Central India',
  },
  {
    id: 'ujjain_mp',
    city: 'Ujjain',
    district: 'Ujjain',
    state: 'Madhya Pradesh',
    latitude: 23.1765,
    longitude: 75.7885,
    region: 'Central India',
  },

  // Rajasthan & Gujarat
  {
    id: 'jaipur_rj',
    city: 'Jaipur',
    district: 'Jaipur',
    state: 'Rajasthan',
    latitude: 26.9124,
    longitude: 75.7873,
    region: 'Western India',
  },
  {
    id: 'kota_rj',
    city: 'Kota',
    district: 'Kota',
    state: 'Rajasthan',
    latitude: 25.2138,
    longitude: 75.8648,
    region: 'Western India',
  },
  {
    id: 'ahmedabad_gj',
    city: 'Ahmedabad',
    district: 'Ahmedabad',
    state: 'Gujarat',
    latitude: 23.0225,
    longitude: 72.5714,
    region: 'Western India',
  },
  {
    id: 'rajkot_gj',
    city: 'Rajkot',
    district: 'Rajkot',
    state: 'Gujarat',
    latitude: 22.3039,
    longitude: 70.8022,
    region: 'Western India',
  },

  // Bihar, West Bengal, South India
  {
    id: 'patna_br',
    city: 'Patna',
    district: 'Patna',
    state: 'Bihar',
    latitude: 25.5941,
    longitude: 85.1376,
    region: 'East India',
  },
  {
    id: 'bardhaman_wb',
    city: 'Bardhaman',
    district: 'Purba Bardhaman',
    state: 'West Bengal',
    latitude: 23.2324,
    longitude: 87.8615,
    region: 'East India',
  },
  {
    id: 'hyderabad_ts',
    city: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    latitude: 17.385,
    longitude: 78.4867,
    region: 'South India',
  },
  {
    id: 'warangal_ts',
    city: 'Warangal',
    district: 'Warangal',
    state: 'Telangana',
    latitude: 17.9689,
    longitude: 79.5941,
    region: 'South India',
  },
  {
    id: 'bengaluru_ka',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    latitude: 12.9716,
    longitude: 77.5946,
    region: 'South India',
  },
];
